-- MySQL Script generated by MySQL Workbench
-- Thu May 21 17:14:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema retail_sales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema retail_sales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `retail_sales` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `retail_sales` ;

-- -----------------------------------------------------
-- Table `retail_sales`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_sales`.`brands` (
  `brand_id` INT NOT NULL,
  `brand_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `retail_sales`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_sales`.`categories` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `retail_sales`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_sales`.`customers` (
  `customer_id` INT NOT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(25) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `street` VARCHAR(200) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `state` VARCHAR(10) NULL DEFAULT NULL,
  `zip_code` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `retail_sales`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_sales`.`stores` (
  `store_id` INT NOT NULL,
  `store_name` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(25) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `street` VARCHAR(200) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `state` VARCHAR(10) NULL DEFAULT NULL,
  `zip_code` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `retail_sales`.`staffs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_sales`.`staffs` (
  `staff_id` INT NOT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `phone` VARCHAR(25) NULL DEFAULT NULL,
  `active` INT NULL DEFAULT NULL,
  `store_id` INT NULL DEFAULT NULL,
  `manager_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`staff_id`),
  INDEX `store_id` (`store_id` ASC) VISIBLE,
  CONSTRAINT `staffs_ibfk_1`
    FOREIGN KEY (`store_id`)
    REFERENCES `retail_sales`.`stores` (`store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `retail_sales`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_sales`.`orders` (
  `order_id` INT NOT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `order_status` INT NULL DEFAULT NULL,
  `order_date` DATE NULL DEFAULT NULL,
  `required_date` DATE NULL DEFAULT NULL,
  `shipped_date` DATE NULL DEFAULT NULL,
  `store_id` INT NULL DEFAULT NULL,
  `staff_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `store_id` (`store_id` ASC) VISIBLE,
  INDEX `staff_id` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `retail_sales`.`customers` (`customer_id`),
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`store_id`)
    REFERENCES `retail_sales`.`stores` (`store_id`),
  CONSTRAINT `orders_ibfk_3`
    FOREIGN KEY (`staff_id`)
    REFERENCES `retail_sales`.`staffs` (`staff_id`),
  CONSTRAINT `orders_ibfk_4`
    FOREIGN KEY (`customer_id`)
    REFERENCES `retail_sales`.`customers` (`customer_id`),
  CONSTRAINT `orders_ibfk_5`
    FOREIGN KEY (`store_id`)
    REFERENCES `retail_sales`.`stores` (`store_id`),
  CONSTRAINT `orders_ibfk_6`
    FOREIGN KEY (`staff_id`)
    REFERENCES `retail_sales`.`staffs` (`staff_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `retail_sales`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_sales`.`products` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(250) NULL DEFAULT NULL,
  `brand_id` INT NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `model_year` INT NULL DEFAULT NULL,
  `list_price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `brand_id` (`brand_id` ASC) VISIBLE,
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `retail_sales`.`brands` (`brand_id`),
  CONSTRAINT `products_ibfk_2`
    FOREIGN KEY (`category_id`)
    REFERENCES `retail_sales`.`categories` (`category_id`),
  CONSTRAINT `products_ibfk_3`
    FOREIGN KEY (`brand_id`)
    REFERENCES `retail_sales`.`brands` (`brand_id`),
  CONSTRAINT `products_ibfk_4`
    FOREIGN KEY (`category_id`)
    REFERENCES `retail_sales`.`categories` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `retail_sales`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_sales`.`order_items` (
  `order_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `list_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `discount` DECIMAL(4,2) NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`, `item_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_items_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `retail_sales`.`orders` (`order_id`),
  CONSTRAINT `order_items_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `retail_sales`.`products` (`product_id`),
  CONSTRAINT `order_items_ibfk_3`
    FOREIGN KEY (`order_id`)
    REFERENCES `retail_sales`.`orders` (`order_id`),
  CONSTRAINT `order_items_ibfk_4`
    FOREIGN KEY (`product_id`)
    REFERENCES `retail_sales`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `retail_sales`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_sales`.`stocks` (
  `store_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`store_id`, `product_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `stocks_ibfk_1`
    FOREIGN KEY (`store_id`)
    REFERENCES `retail_sales`.`stores` (`store_id`),
  CONSTRAINT `stocks_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `retail_sales`.`products` (`product_id`),
  CONSTRAINT `stocks_ibfk_3`
    FOREIGN KEY (`store_id`)
    REFERENCES `retail_sales`.`stores` (`store_id`),
  CONSTRAINT `stocks_ibfk_4`
    FOREIGN KEY (`product_id`)
    REFERENCES `retail_sales`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `retail_sales` ;

-- -----------------------------------------------------
-- Placeholder table for view `retail_sales`.`vw_sales_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_sales`.`vw_sales_summary` (`order_id` INT, `order_date` INT, `order_status` INT, `shipped_date` INT, `required_date` INT, `customer_name` INT, `customer_city` INT, `customer_state` INT, `store_name` INT, `staff_name` INT, `product_name` INT, `brand_name` INT, `category_name` INT, `quantity` INT, `list_price` INT, `discount` INT, `revenue` INT);

-- -----------------------------------------------------
-- Placeholder table for view `retail_sales`.`vw_staff_performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_sales`.`vw_staff_performance` (`staff_name` INT, `store_name` INT, `total_orders` INT, `total_revenue` INT);

-- -----------------------------------------------------
-- Placeholder table for view `retail_sales`.`vw_stock_levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_sales`.`vw_stock_levels` (`store_name` INT, `product_name` INT, `brand_name` INT, `category_name` INT, `stock_available` INT);

-- -----------------------------------------------------
-- View `retail_sales`.`vw_sales_summary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retail_sales`.`vw_sales_summary`;
USE `retail_sales`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `retail_sales`.`vw_sales_summary` AS select `o`.`order_id` AS `order_id`,`o`.`order_date` AS `order_date`,`o`.`order_status` AS `order_status`,`o`.`shipped_date` AS `shipped_date`,`o`.`required_date` AS `required_date`,concat(`c`.`first_name`,' ',`c`.`last_name`) AS `customer_name`,`c`.`city` AS `customer_city`,`c`.`state` AS `customer_state`,`st`.`store_name` AS `store_name`,concat(`sf`.`first_name`,' ',`sf`.`last_name`) AS `staff_name`,`p`.`product_name` AS `product_name`,`b`.`brand_name` AS `brand_name`,`cat`.`category_name` AS `category_name`,`oi`.`quantity` AS `quantity`,`oi`.`list_price` AS `list_price`,`oi`.`discount` AS `discount`,round(((`oi`.`quantity` * `oi`.`list_price`) * (1 - `oi`.`discount`)),2) AS `revenue` from (((((((`retail_sales`.`orders` `o` join `retail_sales`.`order_items` `oi` on((`o`.`order_id` = `oi`.`order_id`))) join `retail_sales`.`customers` `c` on((`o`.`customer_id` = `c`.`customer_id`))) join `retail_sales`.`stores` `st` on((`o`.`store_id` = `st`.`store_id`))) join `retail_sales`.`staffs` `sf` on((`o`.`staff_id` = `sf`.`staff_id`))) join `retail_sales`.`products` `p` on((`oi`.`product_id` = `p`.`product_id`))) join `retail_sales`.`brands` `b` on((`p`.`brand_id` = `b`.`brand_id`))) join `retail_sales`.`categories` `cat` on((`p`.`category_id` = `cat`.`category_id`)));

-- -----------------------------------------------------
-- View `retail_sales`.`vw_staff_performance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retail_sales`.`vw_staff_performance`;
USE `retail_sales`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `retail_sales`.`vw_staff_performance` AS select concat(`sf`.`first_name`,' ',`sf`.`last_name`) AS `staff_name`,`st`.`store_name` AS `store_name`,count(distinct `o`.`order_id`) AS `total_orders`,round(sum(((`oi`.`quantity` * `oi`.`list_price`) * (1 - `oi`.`discount`))),2) AS `total_revenue` from (((`retail_sales`.`orders` `o` join `retail_sales`.`order_items` `oi` on((`o`.`order_id` = `oi`.`order_id`))) join `retail_sales`.`staffs` `sf` on((`o`.`staff_id` = `sf`.`staff_id`))) join `retail_sales`.`stores` `st` on((`o`.`store_id` = `st`.`store_id`))) group by `sf`.`staff_id`,`staff_name`,`st`.`store_name`;

-- -----------------------------------------------------
-- View `retail_sales`.`vw_stock_levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retail_sales`.`vw_stock_levels`;
USE `retail_sales`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `retail_sales`.`vw_stock_levels` AS select `st`.`store_name` AS `store_name`,`p`.`product_name` AS `product_name`,`b`.`brand_name` AS `brand_name`,`cat`.`category_name` AS `category_name`,`sk`.`quantity` AS `stock_available` from ((((`retail_sales`.`stocks` `sk` join `retail_sales`.`stores` `st` on((`sk`.`store_id` = `st`.`store_id`))) join `retail_sales`.`products` `p` on((`sk`.`product_id` = `p`.`product_id`))) join `retail_sales`.`brands` `b` on((`p`.`brand_id` = `b`.`brand_id`))) join `retail_sales`.`categories` `cat` on((`p`.`category_id` = `cat`.`category_id`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
